ProjectMantimentos/src/Mantimentos.App/ViewModels/MantimentoViewModel.cs
using System;
using System.Collections.Generic;


namespace Mantimentos.App.ViewModels
{
    public class MantimentoViewModel
    {
        public Guid Id { get; set; }
        public Guid TipoMantimentoId { get; set; }
        public Guid MarcaId { get; set; }
        public string UnidadeSigla { get; set; }
        public DateTime Validade { get; set; }
        public string Capacidade { get; set; }
      //  public IFormFile ImagemUp { get; set; }
        public string Imagem { get; set; }
        public string ConteudoAtual { get; set; }
        public double Estoque { get; set; }
        public double EstoqueMin { get; set; }
        public MarcaViewModel Marca { get; set; }
        public List<MarcaViewModel> Marcas { get; set; }
        public List<UnidadeMedidaViewModel> UnidadeMedidas { get; set; }
        public TpMantimentoViewModel TpMantimento { get; set; }
        public List<TpMantimentoViewModel> TpMantimentos { get; set; }
        public UnidadeMedidaViewModel UnidadeMedida { get; set; }
        public ICollection<MovimentoViewModel> Movimentos { get; set; }
    }
}

ProjectMantimentos/src/Mantimentos.App/Controllers/MantimentosController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mantimentos.App.Business.Models;
using Mantimentos.App.Business.Interfaces;
using AutoMapper;
using Mantimentos.App.ViewModels;

namespace Mantimentos.App.Controllers
{
    /// <summary>
    /// Controller Mantimentos
    /// Obs.: Todas as controller serão limpas implementando os conseitos do projeto com a criação das Services, de momento não existe a viabilidade de acordo com as diretrizes passadas. 
    /// </summary>

    public class MantimentosController : ExtensionController
    {
        private readonly IMantimentoRepository _MantimentoRepository;
        private readonly IMarcaRepository _marcaRepository;
        private readonly IUnidadeMedidaRepository _unidadeMedidaRepository;
        private readonly ITpMantimentoRepository _tpMantimentoRepository;
        private readonly IMapper _mapper;
        public MantimentosController(IMantimentoRepository MantimentoRepository,
                                     IMapper mapper,
                                     IMarcaRepository marcaRepository,
                                     IUnidadeMedidaRepository unidadeMedidaRepository,
                                     ITpMantimentoRepository tpMantimentoRepository)
        {
            _MantimentoRepository = MantimentoRepository;
            _mapper = mapper;
            _marcaRepository = marcaRepository;
            _unidadeMedidaRepository = unidadeMedidaRepository;
            _tpMantimentoRepository = tpMantimentoRepository;
        }

        public async Task<IActionResult> Index(MantimentoFilterViewModel mantimentoFilterViewModel)
        {
            //Criado a instancia para podermos receber e consultar os mesmos 
            Mantimento mantimento = new()
            {
                TpMantimento = new() 
                { 
                    Nome = mantimentoFilterViewModel.NomeTpMantimento
                },
                Marca = new()
                {
                    Nome = mantimentoFilterViewModel.NomeMarca
                },
                UnidadeMedida = new()
                {
                    Unidade = mantimentoFilterViewModel.NomeUnidade
                }
            };

            ViewBag.NomeTpMantimento = mantimentoFilterViewModel.NomeTpMantimento;
            ViewBag.NomeMarca = mantimentoFilterViewModel.NomeMarca;
            ViewBag.NomeUnidadeMedida = mantimentoFilterViewModel.NomeUnidade;
            return View(_mapper.Map<IEnumerable<MantimentoViewModel>>( await _MantimentoRepository.ObterTDados(mantimento)));
        }

        public async Task<IActionResult> Details(Guid id)
        {
            MantimentoViewModel mantimentoViewModel = await ObterMantimentoId(id);
            if (mantimentoViewModel == null)
            {
                return NotFound();
            }
            return View(mantimentoViewModel);
        }

        public async Task<IActionResult> Create()
        {
            //Obterndo a listagem para no momento da criação do mantimento selecionar os mesmos
            MantimentoViewModel mantimento = new MantimentoViewModel();
            mantimento.Marcas = _mapper.Map<List<MarcaViewModel>>(await _marcaRepository.ObterTodos());
            mantimento.TpMantimentos = _mapper.Map<List<TpMantimentoViewModel>>(await _tpMantimentoRepository.ObterTodos());
            mantimento.UnidadeMedidas = _mapper.Map<List<UnidadeMedidaViewModel>>(await _unidadeMedidaRepository.GetUnidade());

            return PartialView(mantimento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MantimentoViewModel mantimentoViewModel)
        {
            //Passados dados manualmente padrões de criação porque a ideia é que sejam carregados de acordo com as movimentações.
            //A imagem não foi passado uma vez que não será anexado nesse projeto de momento, fica para quando estiver um time melhor.
            if (!ModelState.IsValid) return View(mantimentoViewModel);
            Mantimento mantimento = _mapper.Map<Mantimento>(mantimentoViewModel);
            mantimento.Estoque = 0;
            mantimento.ConteudoAtual = "0";
            mantimento.Imagem = "imagem";
            await _MantimentoRepository.Adicionar(mantimento);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            //Mesma situação do create, recebendo os dados para ser possivel seleção durante a edição
            MantimentoViewModel mantimentoViewModel = await ObterMantimentoId(id);
            mantimentoViewModel.Marcas = _mapper.Map<List<MarcaViewModel>>(await _marcaRepository.ObterTodos());
            mantimentoViewModel.TpMantimentos = _mapper.Map<List<TpMantimentoViewModel>>(await _tpMantimentoRepository.ObterTodos());
            mantimentoViewModel.UnidadeMedidas = _mapper.Map<List<UnidadeMedidaViewModel>>(await _unidadeMedidaRepository.GetUnidade());
            if (mantimentoViewModel == null)
            {
                return NotFound();
            }
            return View(mantimentoViewModel);
        }
       
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id,  MantimentoViewModel mantimentoViewModel)
        {
            if (id != mantimentoViewModel.Id) return NotFound();
            if (!ModelState.IsValid) return View(mantimentoViewModel);
            Mantimento mantimento =  _mapper.Map<Mantimento>(mantimentoViewModel);
            mantimento.Imagem = "imagem";

            await _MantimentoRepository.Atualizar(mantimento);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            MantimentoViewModel mantimentoViewModel = await ObterMantimentoId(id);
            if (mantimentoViewModel == null)
            {
                return NotFound();
            }
            return View(mantimentoViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _MantimentoRepository.Remover(id);
            return RedirectToAction("Index");
        }
        //Metodo ObterMantimentoId criado para melhor visualização de codigo, metodo privado para reduzir necessidade de passar mapeamento de busca de dados por id
        private async Task<MantimentoViewModel> ObterMantimentoId(Guid id)
        {
            return _mapper.Map<MantimentoViewModel>(await _MantimentoRepository.ObterPorId(id));
        }
    }
}

ProjectMantimentos/src/Mantimentos.App/Views/Mantimentos/Create.cshtml
@model Mantimentos.App.ViewModels.MantimentoViewModel



<div class="modal fade modal-mantimento" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form asp-action="Create">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Novo mantimento</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-group">
                                    <label class="control-label">Tipo</label>
                                    <select asp-for="TipoMantimentoId" class="form-control" asp-items="@(new SelectList(Model.TpMantimentos,"Id","Nome"))">
                                        <option></option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Marca</label>
                                    <select asp-for="MarcaId" class="form-control" asp-items="@(new SelectList(Model.Marcas,"Id","Nome"))">
                                        <option></option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Unidade</label>
                                    <select asp-for="UnidadeSigla" class="form-control" asp-items="@(new SelectList(Model.UnidadeMedidas,"Sigla","Unidade"))">
                                        <option></option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Validade" class="control-label"></label>
                                    <input asp-for="Validade" class="form-control" />
                                    <span asp-validation-for="Validade" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Capacidade" class="control-label"></label>
                                    <input type="number" min="0" asp-for="Capacidade" class="form-control" />
                                    <span asp-validation-for="Capacidade" class="text-danger"></span>
                                </div>
                                @*<div class="form-group">
                                        <label asp-for="Imagem" class="control-label"></label>
                                        <input asp-for="Imagem" class="form-control" />
                                        <span asp-validation-for="Imagem" class="text-danger"></span>
                                    </div>*@
                                <div class="form-group">
                                    <label class="control-label">Estoque Mínimo</label>
                                    <input asp-for="EstoqueMin" class="form-control" />
                                    <span asp-validation-for="EstoqueMin" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <a class="btn btn-secondary" asp-action="Index"> <i class="fas fa-times"></i> Sair</a>
                        <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMantimentos/src/Mantimentos.App/Views/Mantimentos/Delete.cshtml
@model Mantimentos.App.ViewModels.MantimentoViewModel

@{
    ViewData["Title"] = "Remover";
}

<h4>Deseja realmente excluir o mantimento?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Validade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Validade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ConteudoAtual)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ConteudoAtual)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estoque)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estoque)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstoqueMin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstoqueMin)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt "></i> Deletar</button>
        <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
    </form>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/Mantimentos/Details.cshtml
@model Mantimentos.App.ViewModels.MantimentoViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Validade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Validade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ConteudoAtual)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ConteudoAtual)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estoque)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estoque)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstoqueMin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstoqueMin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TpMantimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TpMantimento.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UnidadeMedida)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UnidadeMedida.Sigla)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@Model.Id"><i class="fas fa-edit"></i> Editar</a>
    <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/Mantimentos/Edit.cshtml
@model Mantimentos.App.ViewModels.MantimentoViewModel

@{
    ViewData["Title"] = "Editar";
}


<h4>Mantimento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tipo</label>
                <select asp-for="TipoMantimentoId" class="form-control" asp-items="@(new SelectList(Model.TpMantimentos,"Id","Nome"))">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Marca</label>
                <select asp-for="MarcaId" class="form-control" asp-items="@(new SelectList(Model.Marcas,"Id","Nome"))">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Unidade</label>
                <select asp-for="UnidadeSigla" class="form-control" asp-items="@(new SelectList(Model.UnidadeMedidas,"Sigla","Unidade"))">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Validade" class="control-label"></label>
                <input asp-for="Validade" class="form-control" />
                <span asp-validation-for="Validade" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Capacidade" class="control-label"></label>
                <input asp-for="Capacidade" class="form-control" value="@Model.Capacidade" disabled />
                <span asp-validation-for="Capacidade" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
            <label asp-for="Imagem" class="control-label"></label>
            <input asp-for="Imagem" class="form-control" />
            <span asp-validation-for="Imagem" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label class="control-label">Estoque Mínimo</label>
                <input asp-for="EstoqueMin" class="form-control" />
                <span asp-validation-for="EstoqueMin" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
            </div>
            <input type="hidden" asp-for="ConteudoAtual" />
            <input type="hidden" asp-for="Imagem" />
            <input type="hidden" asp-for="Estoque" />
            <input type="hidden" asp-for="Capacidade" />
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMantimentos/src/Mantimentos.App/Views/Mantimentos/Index.cshtml
@model IEnumerable<Mantimentos.App.ViewModels.MantimentoViewModel>

@{
    ViewData["Title"] = "Mantimento";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="Index">
    <div class="row">
        <div class="col-lg-3">
            <label>Tipo Mantimento</label>
            <input type="text" name="NomeTpMantimento" class="form-control form-control-sm" value="@ViewBag.NomeTpMantimento" />
        </div>
        <div class="col-lg-3">
            <label>Marca</label>
            <input type="text" name="NomeMarca" class="form-control form-control-sm" value="@ViewBag.NomeMarca" />
        </div>
        <div class="col-lg-3">
            <label>Unidade</label>
            <input type="text" name="NomeUnidade" class="form-control form-control-sm" value="@ViewBag.NomeUnidadeMedida" />
        </div>
        <div class="col-lg-3">
            <button type="submit" class="btn btn-primary  float-right" style="margin-top:12%"><i class="fas fa-search"></i> Buscar</button>
        </div>
    </div>
</form>
<div class="row" style="margin-top:1%">
    <div class="col-lg-9 "></div>
        <div class="col-lg-3">
            <a class="btn btn-info btn-mantimento text-white float-right"><i class="fas fa-plus"></i> Novo mantimento </a>
        </div>
    </div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>
                      Tipo
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Marca)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Capacidade)
                    </th>
                    <th>
                       Conteúdo Atual
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Estoque)
                    </th>
                    <th>
                       Estoque Min
                    </th>
                    <th>
                        Unidade Medida
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Validade)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    @if (item.TpMantimento.Obrigatorio = true && item.Estoque <= 0)
                    {
                <tr class="alert-danger">
                    <td>
                        @Html.DisplayFor(modelItem => item.TpMantimento.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Capacidade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConteudoAtual)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estoque)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EstoqueMin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnidadeMedida.Sigla)
                    </td>
                    <td>
                        @item.Validade.ToString("dd/MM/yyyy")
                    </td>
                    <td class="text-right">
                        <a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i> </a>
                        @*<a class="btn btn-info " asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle "></i> </a>*@
                        <a class="btn btn-danger  " asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash-alt "></i> </a>
                    </td>
                </tr>
                    }
                    else
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TpMantimento.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Marca.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Capacidade)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ConteudoAtual)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Estoque)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EstoqueMin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UnidadeMedida.Sigla)
                        </td>
                        <td>
                            @item.Validade.ToString("dd/MM/yyyy")
                        </td>
                        <td class="text-right">
                            <a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i> </a>
                            @*<a class="btn btn-info " asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle "></i> </a>*@
                            <a class="btn btn-danger  " asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash-alt "></i> </a>
                        </td>
                    </tr>
                        }
                    }
            </tbody>
        </table>
    </div>
</div>
 
    <div class="modal-mantimento"></div>

    @section Scripts{
        <script type="text/javascript">
        $('.btn-mantimento').click(function () {
            $('.modal-mantimento').load('@Url.Action("Create","Mantimentos")', function () {
                $('.modal-mantimento').modal('show')
            });
        });
        </script>
    }