ProjectMantimentos/src/Mantimentos.App/ViewModels/UnidadeMedidaViewModel.cs
using System;

namespace Mantimentos.App.ViewModels
{
    public class UnidadeMedidaViewModel
    {   
        public string Unidade { get; set; }
        public string Sigla { get; set; }
    }
}

ProjectMantimentos/src/Mantimentos.App/Controllers/UnidadeMedidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mantimentos.App.Business.Models;
using Mantimentos.App.Data.Context;
using Mantimentos.App.Business.Interfaces;
using AutoMapper;
using Mantimentos.App.ViewModels;

namespace Mantimentos.App.Controllers
{
    /// <summary>
    /// Controler Mantimentos
    /// Obs.: Todas as controller serão limpas implementando os conseitos do projeto com a criação das Services, de momento não existe a viabilidade de acordo com as diretrizes passadas. 
    /// </summary>
    public class UnidadeMedidasController : ExtensionController
    {
        private readonly IUnidadeMedidaRepository _UnidadeMedidaRepository;
        private readonly IMapper _mapper;

        public UnidadeMedidasController(IUnidadeMedidaRepository UnidadeMedidaRepository, IMapper mapper)
        {
            _UnidadeMedidaRepository = UnidadeMedidaRepository;
            _mapper = mapper;
        }

        //Atravez do Index ja estamos mapeando e retornando as unidades existentes no banco para ser possivel preencher nossa view
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<UnidadeMedidaViewModel>>(await _UnidadeMedidaRepository.GetUnidade()));
        }
        //Na Detalhes astraves do metodo ObterUnidadeSigla estamos resgatando os dados do repository e retornando a nossa viewModel
        public async Task<IActionResult> Details(string sigla)
        {
            UnidadeMedidaViewModel unidadeMedidaViewModel = await ObterUnidadeSigla(sigla);
            if (unidadeMedidaViewModel == null)
            {
                return NotFound();
            }
            return View(unidadeMedidaViewModel);
        }
        //Chamada do Create, Necessariamente ser PartialView pois estamos trabalhando com um Modal.
        public IActionResult Create()
        {
            return PartialView();
        }
        //Criando, nesse momento é esta sendo  resgatado a viewModel e validando,
        //efetuado o mapper e estornado para uma instancia de unidade preenchemendo a mesma e passado-a mesma
        //para ser salva atrasver do metodo PostUnidade
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UnidadeMedidaViewModel unidadeMedidaViewModel)
        {
            if (!ModelState.IsValid) return View(unidadeMedidaViewModel);
            UnidadeMedida unidadeMedida = _mapper.Map<UnidadeMedida>(unidadeMedidaViewModel);
           _UnidadeMedidaRepository.PostUnidade(unidadeMedida);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(string sigla)
        {
            UnidadeMedidaViewModel unidadeMedidaViewModel = await ObterUnidadeSigla(sigla);
            if (unidadeMedidaViewModel == null)
            {
                return NotFound();
            }
            return View(unidadeMedidaViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string sigla, UnidadeMedidaViewModel unidadeMedidaViewModel)
        {
            if (sigla != unidadeMedidaViewModel.Sigla) return NotFound();
            if (!ModelState.IsValid) return View(unidadeMedidaViewModel);
            UnidadeMedida unidadeMedida = _mapper.Map<UnidadeMedida>(unidadeMedidaViewModel);
            _UnidadeMedidaRepository.PutUnidade(unidadeMedida);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(string sigla)
        {
            UnidadeMedidaViewModel unidadeMedidaViewModel = await ObterUnidadeSigla(sigla);
            if (unidadeMedidaViewModel == null)
            {
                return NotFound();
            }
            return View(unidadeMedidaViewModel);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string sigla)
        {
            _UnidadeMedidaRepository.DeleteUnidade(sigla);
            return RedirectToAction("Index");
        }
        private async Task<UnidadeMedidaViewModel> ObterUnidadeSigla(string sigla)
        {
            return _mapper.Map<UnidadeMedidaViewModel>(await _UnidadeMedidaRepository.GetUnidadeID(sigla));
        }
    }
}

ProjectMantimentos/src/Mantimentos.App/Views/UnidadeMedidas/Create.cshtml
@model Mantimentos.App.ViewModels.UnidadeMedidaViewModel


<div class="modal fade modal-Unidade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form asp-action="Create">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Nova unidade de medida</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="row">
                        <div class="col-md-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Unidade" class="control-label"></label>
                                <input asp-for="Unidade" class="form-control" />
                                <span asp-validation-for="Unidade" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Sigla" class="control-label"></label>
                                <input asp-for="Sigla" class="form-control" />
                                <span asp-validation-for="Sigla" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary" asp-action="Index"> <i class="fas fa-times"></i> Sair</a>
                    <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMantimentos/src/Mantimentos.App/Views/UnidadeMedidas/Delete.cshtml
@model Mantimentos.App.ViewModels.UnidadeMedidaViewModel

@{
    ViewData["Title"] = "Deletar";
}

<h4>Deseja realmente excluir a unidade de medida?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <h4>Categoria</h4>
        </dt>
        <dd class="col-sm-10">
            <h5> @Html.DisplayFor(model => model.Unidade)</h5>
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Sigla" />
        <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt "></i> Deletar</button>
        <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
    </form>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/UnidadeMedidas/Details.cshtml
@model Mantimentos.App.ViewModels.UnidadeMedidaViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"] </h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <h4>Categoria</h4>
        </dt>
        <dd class="col-sm-10">
            <h5>  @Html.DisplayFor(model => model.Unidade)</h5>
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning text-white" asp-action="Edit" asp-route-sigla="@Model.Sigla"><i class="fas fa-edit"></i> </a>
    <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i></a>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/UnidadeMedidas/Edit.cshtml
@model Mantimentos.App.ViewModels.UnidadeMedidaViewModel

@{
    ViewData["Title"] = "Edição";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <h3>Edite a unidade de medida</h3>
                @*<input asp-for="Sigla" class="form-control" />
                <span asp-validation-for="Sigla" class="text-danger"></span>*@
                <input asp-for="Unidade" class="form-control" />
                <span asp-validation-for="Unidade" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Sigla" />
            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMantimentos/src/Mantimentos.App/Views/UnidadeMedidas/Index.cshtml
@model IEnumerable<Mantimentos.App.ViewModels.UnidadeMedidaViewModel>

@{
    ViewData["Title"] = "Unidade de Medida";
}

<h1>@ViewData["Title"]</h1>

<div class="row" style="margin-top:1%">
    <div class="col-lg-9 "></div>
    <div class="col-lg-3">
        <a class="btn btn-info btn-Unidade text-white float-right"><i class="fas fa-plus"></i> Nova Unidade de Medida </a>
    </div>
</div>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Sigla)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unidade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sigla)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unidade)
                </td>
                <td class="text-right">
                    <a class="btn btn-warning text-white" asp-action="Edit" asp-route-sigla="@item.Sigla"><i class="fas fa-edit"></i> </a>
                    <a class="btn btn-info " asp-action="Details" asp-route-sigla="@item.Sigla"><i class="fas fa-info-circle "></i> </a>
                    <a class="btn btn-danger  " asp-action="Delete" asp-route-sigla="@item.Sigla"><i class="fas fa-trash-alt "></i> </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal-Unidade"></div>

@section Scripts{
    <script type="text/javascript">
        $('.btn-Unidade').click(function () {
            $('.modal-Unidade').load('@Url.Action("Create","UnidadeMedidas")', function () {
                $('.modal-Unidade').modal('show')
            });
        });
    </script>
}