ProjectMantimentos/src/Mantimentos.App/ViewModels/MovimentoViewModel.cs
using Mantimentos.App.Business.Enums;
using System;
using System.Collections.Generic;

namespace Mantimentos.App.ViewModels
{
    public class MovimentoViewModel
    {
        public Guid Id { get; set; }
        public Guid MantimentoId { get; set; }
        public double Quantidade { get; set; }
        public string Nome { get; set; }
        public TipoMovimento TipoMovimento { get; set; }
        public List<MantimentoViewModel> Mantimentos { get; set; }
        public List<MovimentoSelectViewModel> MovimentoSelectViewModel { get; set; }
    }
}

ProjectMantimentos/src/Mantimentos.App/Controllers/MovimentosController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mantimentos.App.Business.Models;
using Mantimentos.App.Business.Interfaces;
using AutoMapper;
using Mantimentos.App.ViewModels;
using System.Linq;

namespace Mantimentos.App.Controllers
{/// <summary>
/// Controller Movimentos.
/// Obs.: Não foi implementado edição dos movimentos nem mesmo esclusão pois de momento não é interessante. Caso necessario seria implementado com maior viabilidade
/// Obs.: Todas as controller serão limpas implementando os conseitos do projeto com a criação das Services, de momento não existe a viabilidade de acordo com as diretrizes passadas. 
/// </summary>
    public class MovimentosController : ExtensionController
    {
        private readonly IMovimentoRepository _MovimentoRepository;
        private readonly IMantimentoRepository _mantimentoRepository;
        private readonly IMapper _mapper;
        public MovimentosController(IMovimentoRepository MovimentoRepository,
            IMapper mapper,
            IMantimentoRepository mantimentoRepository)
        {
            _MovimentoRepository = MovimentoRepository;
            _mapper = mapper;
            _mantimentoRepository = mantimentoRepository;
        }
        //Recebido na index todos os movimentos ja criados.
        //Alem disso como nosso mantimento é de uma forma composta exemplo temos LEITE que é o Tipo de Mantimento, e esse produto é diferenciado com a marca.
        //Foi necessario retornar algo mais viavel ao usuario, sendo assim foi criado em um Foreach o item.nome que retorna essa concatenação.
        //Metodo  de concatenação criado tambem para o Create.
        public async Task<IActionResult> Index()
        {
            List<MovimentoViewModel> movimentoViewModels = _mapper.Map<List<MovimentoViewModel>>(await _MovimentoRepository.ObterTodos());

            List<Mantimento> mantimentos = (await _mantimentoRepository.ObterNome()).ToList();
            foreach (var item in movimentoViewModels)
            {
                var teste = mantimentos.Where(f => f.Id == item.MantimentoId).FirstOrDefault();
                item.Nome = $"{teste.TpMantimento.Nome}-{teste.Marca.Nome}";
            }

            return View(movimentoViewModels);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            MovimentoViewModel movimentoViewModel = await ObterMovimentoId(id);
            if (movimentoViewModel == null)
            {
                return NotFound();
            }
            return View(movimentoViewModel);
        }
        public async Task<IActionResult> Create()
        {
            MovimentoViewModel movimentoViewModel = new();
            movimentoViewModel.MovimentoSelectViewModel = (await _mantimentoRepository.ObterNome()).ToList().Select(f => new MovimentoSelectViewModel()
            {
                IdMantimento = f.Id,
                Nome = $"{f.TpMantimento.Nome}-{f.Marca.Nome}"
            }).ToList();
            return PartialView(movimentoViewModel);
        }

        //Criado metodo AtualizarMantimentoPorId para poder ser possivel a movimentação do estoque e recalculos necessarios.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovimentoViewModel movimentoViewModel)
        {
            if (!ModelState.IsValid) return View(movimentoViewModel);
            Movimento movimento = _mapper.Map<Movimento>(movimentoViewModel);
            await _MovimentoRepository.Adicionar(movimento);
            _mantimentoRepository.AtualizarMantimentoPorId(movimentoViewModel.MantimentoId, movimentoViewModel.Quantidade, movimentoViewModel.TipoMovimento);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            MovimentoViewModel movimentoViewModel = await ObterMovimentoId(id);
            if (movimentoViewModel == null)
            {
                return NotFound();
            }
            return View(movimentoViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, MovimentoViewModel movimentoViewModel)
        {
            if (id != movimentoViewModel.Id) return NotFound();
            if (!ModelState.IsValid) return View(movimentoViewModel);
            Movimento movimento = _mapper.Map<Movimento>(movimentoViewModel);
            await _MovimentoRepository.Atualizar(movimento);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            MovimentoViewModel movimentoViewModel = await ObterMovimentoId(id);
            if (movimentoViewModel == null)
            {
                return NotFound();
            }
            return View(movimentoViewModel);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _MovimentoRepository.Remover(id);
            return RedirectToAction("Index");
        }
        //Metodo ObterMovimentoId criado para melhor visualização de codigo, metodo privado para reduzir necessidade de passar mapeamento de busca de dados por id
        private async Task<MovimentoViewModel> ObterMovimentoId(Guid id)
        {
            return _mapper.Map<MovimentoViewModel>(await _MovimentoRepository.ObterPorId(id));
        }
    }
}

ProjectMantimentos/src/Mantimentos.App/Views/Movimentos/Create.cshtml
@model Mantimentos.App.ViewModels.MovimentoViewModel

<div class="modal fade modal-movimento" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form asp-action="Create">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Novo Movimento</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="row">
                        <div class="col-md-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <h7>Mantimento</h7>
                                <select asp-for="MantimentoId" class="form-control" asp-items="@(new SelectList(Model.MovimentoSelectViewModel,"IdMantimento","Nome"))">
                                    <option></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Quantidade" class="control-label"></label>
                                <input asp-for="Quantidade" class="form-control" />
                                <span asp-validation-for="Quantidade" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                               <h7>Movimento</h7><br />
                                <input type="radio" value="1" asp-for="TipoMovimento" checked /> Entrada <br />
                                <input type="radio" value="2" asp-for="TipoMovimento" /> Saída
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary" asp-action="Index"> <i class="fas fa-times"></i> Sair</a>
                    <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMantimentos/src/Mantimentos.App/Views/Movimentos/Delete.cshtml
@model Mantimentos.App.ViewModels.MovimentoViewModel


@{
    ViewData["Title"] = "Remover";
}

<h4>Deseja realmente excluir o movimento?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MantimentoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MantimentoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoMovimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoMovimento)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt "></i> Deletar</button>
        <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
    </form>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/Movimentos/Details.cshtml
@model Mantimentos.App.ViewModels.MovimentoViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MantimentoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MantimentoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoMovimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoMovimento)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@Model.Id"><i class="fas fa-edit"></i> Editar</a>
    <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/Movimentos/Edit.cshtml
@model Mantimentos.App.ViewModels.MovimentoViewModel

@{
    ViewData["Title"] = "Edição";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MantimentoId" class="control-label"></label>
                <input asp-for="MantimentoId" class="form-control" />
                <span asp-validation-for="MantimentoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoMovimento" class="control-label"></label>
                <div>
                    <input type="radio" value="1" asp-for="TipoMovimento" checked="@((int)Model.TipoMovimento == 1)" /> Entrada
                    <input type="radio" value="2" asp-for="TipoMovimento" checked="@((int)Model.TipoMovimento == 2)" /> Saida
                </div>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Salvar</button>
                <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectMantimentos/src/Mantimentos.App/Views/Movimentos/Index.cshtml
@model IEnumerable<Mantimentos.App.ViewModels.MovimentoViewModel>

@{
    ViewData["Title"] = "Movimento";
}

<h1>@ViewData["Title"]</h1>

<div class="row" style="margin-top:1%">
    <div class="col-lg-9 "></div>
    <div class="col-lg-3">
        <a class="btn btn-info btn-movimento text-white float-right"><i class="fas fa-plus"></i> Novo Movimento </a>
    </div>
</div>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
               Mantimento
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th>
               Movimento
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoMovimento)
            </td>
            <td class="text-right">
                @*<a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i> </a>*@
                @*<a class="btn btn-info " asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle "></i> </a>*@
                @*<a class="btn btn-danger  " asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash-alt "></i> </a>*@
            </td>
        </tr>
        }
    </tbody>
</table>
<div class="modal-movimento"></div>

@section Scripts{
    <script type="text/javascript">
        $('.btn-movimento').click(function () {
            $('.modal-movimento').load('@Url.Action("Create","Movimentos")', function () {
                $('.modal-movimento').modal('show')
            });
        });
    </script>
}