ProjectMantimentos/src/Mantimentos.App/ViewModels/TpMantimentoViewModel.cs
using System;
using System.Collections.Generic;

namespace Mantimentos.App.ViewModels
{
    public class TpMantimentoViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public bool Obrigatorio { get; set; }
        public CategoriaViewModel Categoria { get; set; }
        public List<CategoriaViewModel> Categorias { get; set; }
        public List<TpMantimentoCategoriaViewModel> TpMantimentoCategoriaViewModels { get; set; }
        public Guid[] CategoriaIds { get; set; }
    }
}

ProjectMantimentos/src/Mantimentos.App/Controllers/TpMantimentosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mantimentos.App.Business.Models;
using Mantimentos.App.Business.Interfaces;
using System;
using AutoMapper;
using Mantimentos.App.ViewModels;
using System.Collections.Generic;
using X.PagedList;
using System.Linq;

namespace Mantimentos.App.Controllers
{
    /// <summary>
    /// Controller TpMantimentos
    /// Obs.: Todas as controller serão limpas implementando os conseitos do projeto com a criação das Services, de momento não existe a viabilidade de acordo com as diretrizes passadas. 
    /// </summary>
    public class TpMantimentosController : ExtensionController
    {
        private readonly ITpMantimentoRepository _TpMantimentoRepository;
        private readonly ICategoriaRepository _categoriaRepository;
        private readonly IMapper _mapper;

        public TpMantimentosController(ITpMantimentoRepository TpMantimentoRepository,
                                        IMapper mapper,
                                        ICategoriaRepository categoriaRepository)
        {
            _TpMantimentoRepository = TpMantimentoRepository;
            _mapper = mapper;
            _categoriaRepository = categoriaRepository;
        }
        public async Task<IActionResult> Index(TpMantimentoFilterViewModel tpMantimentoFilterViewModel)
        {
            //Já na index criado a utilização de paglist,
            //nesse ponto foi encontrado um desafio que era retornar toda a listagem de tpMantimentos Categoria de acordo com cada TpMantimento.
            //Foi feito um foreach para popular De acordo com cada Tipo de mantimento suas categorias. 

            const int itensPorPagina = 5;
            int numeroPagina = (tpMantimentoFilterViewModel.pag ?? 1);

            ViewBag.Nome = tpMantimentoFilterViewModel.Nome;

            TpMantimento tpfilter = new()
            {
                Nome = tpMantimentoFilterViewModel.Nome
            };

            List<TpMantimento> mantimentos = await  _TpMantimentoRepository.ObterTDados(tpfilter);
            List<TpMantimentoViewModel> query2 =  _mapper.Map<List<TpMantimentoViewModel>>(mantimentos);
            foreach (var item in query2)
            {
                TpMantimento t = mantimentos.Where(c => c.Id == item.Id).FirstOrDefault();

                List<TpMantimentoCategoriaViewModel> t2 = t.TpMantimentoCategoria.Select(x=> new TpMantimentoCategoriaViewModel()
                {
                    CategoriaId = x.CategoriaId
                }).ToList();
                    
                foreach (var item2 in t2)
                {
                    item2.Categoria = _mapper.Map<CategoriaViewModel>(await _categoriaRepository.ObterPorId(item2.CategoriaId));
                }
                item.TpMantimentoCategoriaViewModels = t2;
            }
            IPagedList<TpMantimentoViewModel> query = query2.ToPagedList(numeroPagina, itensPorPagina);
            return View(query);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            TpMantimentoViewModel tpMantimentoViewModel = await ObterTpMantimentoId(id);
            if (tpMantimentoViewModel == null)
            {
                return NotFound();
            }
            return View(tpMantimentoViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            TpMantimentoViewModel TpmantimentoViewModel = new();
            TpmantimentoViewModel.Categorias = await PopularCategorias();

            return PartialView(TpmantimentoViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Criar(TpMantimentoViewModel tpMantimentoViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!ModelState.IsValid) return View(tpMantimentoViewModel);
                    TpMantimento tpMantimento = _mapper.Map<TpMantimento>(tpMantimentoViewModel);
                    tpMantimento.Id = Guid.NewGuid();

                    List<TpMantimentoCategoria> categorias = new();
                    foreach (var item in tpMantimentoViewModel.CategoriaIds)
                    {
                        Categoria categoria = await _categoriaRepository.ObterPorId(item);
                        TpMantimentoCategoria tpcategoria = new()
                        {
                            Id = Guid.NewGuid(),
                            CategoriaId = item,
                            MantimentoTpId = tpMantimento.Id,
                        };
                        categorias.Add(tpcategoria);
                    }
                    tpMantimento.TpMantimentoCategoria.AddRange(categorias);
                    await _TpMantimentoRepository.Adicionar(tpMantimento);
                    return RedirectToAction(nameof(Index));
                }
                return View(tpMantimentoViewModel);
            }
             catch (Exception ex)
            {
                throw;
            }
         
        }
        public async Task<IActionResult> Edit(Guid id)
        {

            TpMantimentoViewModel tpMantimentoViewModel = await ObterTpMantimentoId(id);
            if (tpMantimentoViewModel == null)
            {
                return NotFound();
            }
            tpMantimentoViewModel.Categorias = await PopularCategorias();
            return View(tpMantimentoViewModel);
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(TpMantimentoViewModel tpMantimentoViewModel)
        {
            //ja no editar é necessario desconstruir as categorias ja relacionadas em TpMantiemntoCategoria e permitir recriar.
            //Sendo assim uma vez que a edição passou teve a alteração é removido o que existia relacionado de tpMantimentos e recriado com base na edição.
            //Essa parte é necessario ser melhorada e será quando possivel pois perde a essecia do Solid uma vez que não tem sentindo ter mais de uma ação.
            try
            {
                if (ModelState.IsValid)
                {
                    if (!ModelState.IsValid) return View(tpMantimentoViewModel);
                    _TpMantimentoRepository.RemoverTpMantimentoCategoriaById(tpMantimentoViewModel.Id);
                    TpMantimento tpMantimento = _mapper.Map<TpMantimento>(tpMantimentoViewModel);

                    await _TpMantimentoRepository.Atualizar(tpMantimento);
                    foreach (var item in tpMantimentoViewModel.CategoriaIds)
                    {
                        Categoria categoria = await _categoriaRepository.ObterPorId(item);
                        TpMantimentoCategoria tpcategoria = new()
                        {
                            Id = Guid.NewGuid(),
                            CategoriaId = item,
                            MantimentoTpId = tpMantimento.Id,
                        };
                        _TpMantimentoRepository.AdicionarTpMantimentoCategoria(tpcategoria);
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(tpMantimentoViewModel);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            TpMantimentoViewModel tpMantimentoViewModel = await ObterTpMantimentoId(id);
            if (tpMantimentoViewModel == null)
            {
                return NotFound();
            }
            return View(tpMantimentoViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _TpMantimentoRepository.Remover(id);
            return RedirectToAction("Index");
        }
        //Criado o metodo ObterTpMantimentoId para não ter necessidade de passar sempre o mapeamento no codigo, deixando mais Clean.
        private async Task<TpMantimentoViewModel> ObterTpMantimentoId(Guid id)
        {
            return _mapper.Map<TpMantimentoViewModel>(await _TpMantimentoRepository.ObterPorId(id));
        }
        //Criado o metodo PopularCategorias para coletarmos a lista das categorias que seram utilizadas para criação e edição.
        private async Task<List<CategoriaViewModel>> PopularCategorias()
        {
            List<CategoriaViewModel> categoria = _mapper.Map<List<CategoriaViewModel>>(await _categoriaRepository.ObterTodos());
            return categoria;
        }
    }
}

ProjectMantimentos/src/Mantimentos.App/Views/TpMantimentos/Create.cshtml
@model Mantimentos.App.ViewModels.TpMantimentoViewModel

<div class="modal fade modal-tpmantimento" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form>
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Novo tipo mantimento</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="row">
                        <div class="col-md-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <h5>Categorias</h5>
                                    </div>
                                </div>
                                        <div class="row">
                                            <div class="col-lg-12">

                                                @foreach (var item in Model.Categorias)
                                                {
                                                    <div class="form-group form-check">
                                                        <label class="form-check-label">
                                                            <input type="checkbox" class="form-check-input input-check-categoria" data-id="@item.Id" />  @item.CategoriaNome
                                                        </label>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Nome" class="control-label"></label>
                                        <input asp-for="Nome" class="form-control nome-tp" />
                                        <span asp-validation-for="Nome" class="text-danger"></span>
                                    </div>
                                    <div class="form-group form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input input-check-obg" asp-for="Obrigatorio" /> @Html.DisplayNameFor(model => model.Obrigatorio)
                                        </label>
                                    </div>
                                </div>
                            </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary" asp-action="Index"> <i class="fas fa-times"></i> Sair</a>
                    <button type="button" class="btn btn-success" onclick="SalvarTpMantimento()"><i class="fas fa-check"></i> Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>

    <script type="text/javascript">
        function SalvarTpMantimento() {
            debugger;
            var lista = Array();
            $('.input-check-categoria').each(function () {
                if ($(this).is(':checked')) {
                    lista.push($(this).attr('data-id'));
                }
            });

            $.ajax({
                method: "POST",
                url: "TpMantimentos/Criar",
                data: {
                    Nome: $('.nome-tp').val(),
                    Obrigatorio: $('.input-check-obg').prop('checked'),
                    CategoriaIds: lista
                }
            }).done(function (msg) {
                $('.modal-tpmantimento').modal('hide');
                location.reload();
            })
            .fail(function (jqXHR, textStatus, msg) {
                alert(msg);
            });

        };
    </script>

ProjectMantimentos/src/Mantimentos.App/Views/TpMantimentos/Delete.cshtml
@model Mantimentos.App.ViewModels.TpMantimentoViewModel

@{
    ViewData["Title"] = "Remover";
}

<h4>Deseja realmente excluir este tipo de mantimento?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <h4>Nome</h4>
        </dt>
        <dd class="col-sm-10">
            <h5> @Html.DisplayFor(model => model.Nome)</h5>
        </dd>

        @*<dt class="col-sm-2">
            <h4>Obrigatorio?</h4>
        </dt>
        <dd class="col-sm-10">
            <h5> @Html.DisplayFor(model => model.Obrigatorio)</h5>
        </dd>*@

        @*<dt class="col-sm-2">
            <h4>Categoria</h4>
        </dt>
        <dd class="col-sm-10">
            <h5> @Html.DisplayFor(model => model.Categoria.CategoriaNome)</h5>
        </dd>*@
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt "></i> Deletar</button>
        <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
    </form>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/TpMantimentos/Details.cshtml
@model Mantimentos.App.ViewModels.TpMantimentoViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Obrigatorio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Obrigatorio)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>*@
        @*<dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoria.CategoriaNome)
        </dd>*@
    </dl>
</div>
<div>
    <a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@Model.Id"><i class="fas fa-edit"></i> Editar</a>
    <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
</div>

ProjectMantimentos/src/Mantimentos.App/Views/TpMantimentos/Edit.cshtml
@model Mantimentos.App.ViewModels.TpMantimentoViewModel

@{
    ViewData["Title"] = "Edição";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        <h5>Categorias</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">

                        @foreach (var item in Model.Categorias)
                        {
                            <div class="form-group form-check">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input input-check-categoria" data-id="@item.Id" />  @item.CategoriaNome
                                </label>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control nome-tp" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input input-check-obg" asp-for="Obrigatorio" /> @Html.DisplayNameFor(model => model.Obrigatorio)
                </label>
            </div>
            <input type="hidden" asp-for="Id" value="@Model.Id" id="hidden-id" />
            <div class="form-group">
                <button type="button" class="btn btn-success" onclick="SalvarTpMantimento()"><i class="fas fa-check"></i> Salvar</button>
                <a class="btn btn-info" asp-action="Index"><i class="fas fa-chevron-left"></i> Retornar a lista</a>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
        function SalvarTpMantimento() {
            debugger;
            var lista = Array();
            $('.input-check-categoria').each(function ()
            {
                if ($(this).is(':checked')) {
                    lista.push($(this).attr('data-id'));
                }
            });
            $.ajax({
                method: "POST",
                url: '@Url.Action("Editar","TpMantimentos")',
                data: {
                    Id: $('#hidden-id').val(),
                    Nome: $('.nome-tp').val(),
                    Obrigatorio: $('.input-check-obg').prop('checked'),
                    CategoriaIds: lista
                }
            }).done(function (msg) {
               location.href = '@Url.Action("Index", "TpMantimentos")';
            })
                .fail(function (jqXHR, textStatus, msg) {
                    alert(msg);
                });
        };
</script>

ProjectMantimentos/src/Mantimentos.App/Views/TpMantimentos/Index.cshtml
@model X.PagedList.IPagedList<Mantimentos.App.ViewModels.TpMantimentoViewModel>
@using X.PagedList.Mvc.Core;


@{
    ViewData["Title"] = "Tipo de Mantimentos";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="Index">
    <div class="row">
        <div class="col-lg-6">
            <label>Descrição</label>
            <input type="text" name="Nome" class="form-control form-control-sm" value="@ViewBag.Nome" />
        </div>
        <div class="col-lg-3">
            <button type="submit" class="btn btn-primary  float-left" style="margin-top:10%"><i class="fas fa-search"></i> Buscar</button>
        </div>
        <div class="col-lg-3">
            <a class="btn btn-info btn-tpmantimento text-white float-right" style="margin-top:10%"><i class="fas fa-plus"></i> Novo Tipo Mantimento </a>
        </div>
    </div>
</form>
<div class="row" style="margin-top:1%">
<div class="col-lg-12">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Obrigatoriedade
                </th>
                <th>
                    Categoria
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Obrigatorio)
                    </td>
                    <td>
                        @foreach (var item2 in  item.TpMantimentoCategoriaViewModels)
                        {
                            <p>
                                @item2.Categoria.CategoriaNome
                            </p>
                        }
                    </td>
                    <td class="text-right">
                        <a class="btn btn-warning text-white" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i> </a>
                        <a class="btn btn-info " asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle "></i> </a>
                        <a class="btn btn-danger  " asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash-alt "></i> </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
</div>

<div class="modal-tpmantimento"></div>

@Html.PagedListPager(Model, pag => Url.Action("Index", new { pag }))

@section Scripts{
    <script type="text/javascript">
        $('.btn-tpmantimento').click(function () {
            $('.modal-tpmantimento').load('@Url.Action("Create","TpMantimentos")', function () {
                $('.modal-tpmantimento').modal('show')
            });
        });
    </script>
}